/* QUESTÃO 1 */

SELECT P.NOME, E.EVENTO FROM TABELA_PESSOA AS P, TABELA_EVENTO AS E WHERE P.ID = E.PESSOA_ID;

/* QUESTÃO 2 */

SELECT P.NOME FROM TABELA_PESSOA AS P WHERE P.NOME LIKE '%DOE';

/* QUESTÃO 3 */

INSERT INTO TABELA_EVENTO(ID, EVENTO, PESSOA_ID) VALUES (5, 'Evento E', 5);

/* QUESTÃO 4 */

UPDATE TABELA_EVENTO SET PESSOA_ID = 1 WHERE EVENTO = 'Evento D';

/* QUESTÃO 5 */

DELETE FROM TABELA_EVENTO WHERE EVENTO = 'Evento B';

/* QUESTÃO 6 */

DELETE FROM TABELA_PESSOA WHERE ID NOT IN (SELECT PESSOA_ID FROM TABELA_EVENTO);

/* QUESTÃO 7 */

ALTER TABLE TABELA_PESSOA ADD idade int;

/* QUESTÃO 8 */

CREATE TABLE TABELA_TELEFONE (
    ID INT NOT NULL PRIMARY KEY,
    TELEFONE VARCHAR(200),
    PESSOA_ID INT NOT NULL REFERENCES TABELA_PESSOA(ID)
);

/* QUESTÃO 9 */

CREATE UNIQUE INDEX  TELEFONE ON TABELA_TELEFONE (TELEFONE);

/* QUESTÃO 10 */

ALTER TABLE TABELA_TELEFONE DROP INDEX TELEFONE;
DROP TABLE TABELA_TELEFONE;